andrewhickman/fs-err

src/errors.rs, src/lib.rs
Closes #1.
This PR converts the crate's public functions to return `std::io::Error` instead of a custom error type. I introduced a new custom error type that's internal to the crate and then updated all interfaces to use it.
This is a breaking change!
=> Use std::io::Error instead of own error type

src/errors.rs, src/lib.rs
Closes #5.
This brings an equivalent API to `fs::copy` into fs-err. I added a new inner error type instead of expanding the existing error type since this is the only variant with two paths involved right now.
=> Add CopyError and implement fs::copy

Cargo.toml, README.md, README.tpl, src/file.rs, src/lib.rs
Closes #6.
This PR is still early, but I'm opening it now so you can take a look before I get too far in.
I thought this would be a good application of [cargo-readme](https://github.com/livioribeiro/cargo-readme) and so the source of truth for `README.md` is contained in `src/lib.rs`. I also took the time to move the `File` struct into its own file because `lib.rs` was getting bigger. This helps prepare for #4, too.
There are no functionality changes in this PR, just documentation ones.
=> Documentation and marketing-speak

CHANGELOG.md, src/lib.rs
Closes #13.
Another very small PR. This should finish up most of the reading APIs that I need to adopt fs-err in a lot of my projects!
I can submit larger PRs if you'd prefer. Most of these small PRs to reach coverage are going to be pretty mechanical and easy to review I imagine.
=> Implement fs_err::metadata

src/errors.rs, src/lib.rs
=> Add `remove` apis

.github/workflows/ci.yml
Now that we have Windows-specific code, it would be a good idea to run fs-err's CI pipeline on Windows in addition to Linux.
Because of the changes in https://github.com/andrewhickman/fs-err/commit/f61ae29f9e8962f8d4f1d51fcd6262cecc0e4e44, I believe this CI will currently fail on Windows.
=> Add Windows to build matrix and turn off fast fail

src/errors.rs, src/lib.rs
Closes #10.
Similar to #16, we'll want to come back to this in the future and flesh out the implementation to get better errors. I think it's useful to get to as close to feature parity with `std::fs`, though!
=> Implement create_dir and create_dir_all

src/errors.rs, src/lib.rs
Adds the following functions
* canonicalize
* hard link
* read_link
* rename
* symlink_metadata
* soft_link
which should be all missing ones except for `set_permissions`. I'm unsure how to handle the error for that one. Ideally, the error message would also contain what permissions were attempted to be set, but `Permissions` does not implement `Display`.
We could just leave it at the path. That's already more useful than `std`.
Fixes #24
=> Add missing functions

src/lib.rs, src/path.rs
This PR is based on #25.
`Path` has some nice methods which are just shortcuts for free functions in `std::fs`. `path.some_fn()` => `std::fs::some_fn(path)`. Having to translate such calls to free function calls to benefit from this crate is bothersome.
This PR adds aliases that work the same way except they call `fs_err::some_fn`. Because inherent methods take precedence over trait methods, they must have different names. I have simply appended `_err` to all method names.
I invite bike shedding on the method names and the entire approach.
Defining an extension trait is easier than creating a wrapper struct (unless you're abusing `Deref`), but also more error prone for the user as they have to make sure to call the right method manually.
=> Add aliases to std::path::Path via extension trait

src/file.rs, src/lib.rs, src/open_options.rs
Doesn't contain os-specific extensions, yet.
This also deprecates `File::from_options` as that seems to have only been defined to avoid wrapping `OpenOptions`.
That function could also be kept, but then it should work with both `fs_err::OpenOptions` and `std::fs::OpenOptions`. You'd have to introduce a new type parameter (breaking change) and some way to convert `fs_err::OpenOptions` to `std::fs::OpenOptions` (can't be `AsRef` btw, but `Borrow` would work).
I don't think it's worth it. It only exists in `fs_err` so the only people affected by deprecation are old users of `fs_err`. People migrating to the crate after this PR would never need the function.
=> add OpenOptions wrapper

src/lib.rs
As I mentioned in #25, I initially left this out because I wasn't sure how to include the permissions in the error message, but I noticed that `File::set_permissions` already exists and also just doesn't mention the exact permissions in the message.
This does the same. With this, all free functions in `std::fs` have wrappers.
=> add set_permissions()

CHANGELOG.md, src/errors.rs, src/file.rs, src/lib.rs, src/open_options.rs, src/os.rs, src/os/unix.rs, src/os/windows.rs, src/path.rs
* Added `symlink` for unix platforms
* Added `symlink_file` and `symlink_dir` for windows
* Implemented os-specific extension traits for `File`
- `std::os::unix::io::{AsRawFd, IntoRawFd}`
- `std::os::windows::io::{AsRawHandle, IntoRawHandle}`
- Added trait wrappers for `std::os::{unix, windows}::fs::FileExt` and implemented them for `fs_err::File`
* Implemented os-specific extension traits for `OpenOptions`
- Added trait wrappers for `std::os::{unix, windows}::fs::OpenOptionsExt` and implemented them for `fs_err::OpenOptions`
I believe I have implemented all the os-specific extension traits of the three major platforms (unix, linux, windws) for which wrappers are already defined. The rest will need to be added after the missing wrappers are added (cf #29).
(Thank god trait methods inherit …
=> Add os specific APIs

CHANGELOG.md, src/errors.rs, src/file.rs, src/lib.rs, src/open_options.rs, src/os/unix.rs, src/os/windows.rs
Fixes #23.
* Most functions only need a `PathBuf` in the error case. We can just call `as_ref()` early and build a PathBuf in the error case. We can then also leave out the `Into<PathBuf>` bound.
This is done wherever possible.
* A few APIs always need a `PathBuf`. For those `Into<PathBuf>` is more efficient and the speedup potentially important.
It does mean that the API differs from `std`. That causes incompatibility for users who write generic functions themselves which follow the `std` convention of taking `AsRef<Path>`. They can't use `fs_err` inside those without code changes, but the necessary changes are very minor.
This is done for `fs_err::File` constructors and `fs_err::read_dir`.
* Three functions always construct a `PathBuf`, but don't actually need it. They only do because …
=> Convert generic types early

src/file.rs
This adds the `.into()` and `.from()` traits to easily convert a `fs_err::File` into an `std::fs::File`.
Calling `file.into()` is quite a bit more intuitive and elegant than calling `file.into_parts().0`.
This especially useful when using` fs-err` in libraries if one doesn't want to expose the `fs-err::File` type.
=> Add Into impl for std::fs::File

.github/workflows/ci.yml, src/dir.rs, src/errors.rs, src/file.rs, src/lib.rs, src/open_options.rs, src/os/unix.rs, src/os/windows.rs
First of all, thanks for providing this library. I'm currently thinking about using it in my projects :).
1. Fixes clippy issues
2. Fixes naming of `Error::new()`. `new()` is paradigmatically used as a constructor call, but in this case `Error::new()` was building a new io::Error instead of the library internal `Error`.
3. The CI wasn't properly reporting clippy warnings. I streamlined it to the current de-facto standard that's used by many established projects.
=> Fix clippy and ci

.github/workflows/ci.yml, Cargo.toml, src/file.rs
This PR implements I/O safety traits on `File`. I implemented `AsFd/AsHandle` and `Into<OwnedFd/OwnedHandle>`, although I wasn't able to implement `From<OwnedFd>` since that does not come with path information.
See also: sunfishcode/io-lifetimes#38
=> Implement I/O safety traits

Cargo.toml, src/lib.rs, src/tokio/dir_builder.rs, src/tokio/file.rs, src/tokio/mod.rs, src/tokio/open_options.rs, src/tokio/read_dir.rs
This adds in wrappers for all of the currently publicly exposed types in `tokio::fs`. This currently does not include conversions for `OwnedFd` or `BorrowedFd`, but the rest were a fairly straightforward wrapping.
Resolves #36
=> Add `tokio::fs` wrappers

src/dir.rs, src/file.rs, src/lib.rs, src/open_options.rs, src/os/unix.rs, src/os/windows.rs, src/path.rs, src/tokio/dir_builder.rs, src/tokio/file.rs, src/tokio/mod.rs, src/tokio/open_options.rs, src/tokio/read_dir.rs
This implements #45.
While working on it I noticed that the wrapper for the Windows-specific `tokio::fs::symlink_dir()` appears misnamed as `fs_err::tokio::symlink()` (instead of the expected `fs_err::tokio::symlink_dir()`), so I fixed that as well - but in a separate commit.
=> Improve rustdoc of wrapped functions

src/errors.rs
Recently I learned about glob imports of enums and how they interact with match statements. Basically, glob imports of an enum that are used with a `match` can be a footgun. Refer to this playground:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=9f0ce5f074f7b4a71f487ae8c6a1902d
So instead of a glob import, create a short alias of ErrorKind.
=> Removes glob import of ErrorKind within Display

.github/workflows/ci.yml, CHANGELOG.md, Cargo.toml, src/errors.rs, src/lib.rs
close #59
Changes the default behavior so that the output in the readme now matches the output a user would see when they use the library. Specifically, it now includes the original `std::io::Error` in the output.
It introduces a feature `anyhow`. By default:
- By default: fs-err will include `std::io::Error` in the Display output, and return `None` from `Error::source()`
- With `anyhow` fs-err will not include std::io::Error in the Display output, and return `Some(std::io::Error)` from `Error::source()`
This is based on the guidance from #51. That discussion links to this 2020 discussion https://github.com/rust-lang/project-error-handling/issues/23 that suggests that you should either print the source and return `None` from `Error::source()` …
=> Show source by default, add feature to hide it

src/file.rs, src/tokio/file.rs
I've wanted at least one of these before, don't remember which one exactly 😄 
Closes #56.
=> Add missing File / OpenOptions constructors

build.rs, src/errors.rs, src/file.rs
=> Wrap locking methods added to `File` in Rust 1.89 (#74)
